# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Trigger OSS to Enterprise Merge
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
      - release/**

jobs:
  trigger-oss-merge:
    # run this only on merge events in OSS repo
    if: ${{ github.event.pull_request.merged && github.repository == 'hashicorp/consul' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Merge
        env:
          GH_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        run: |
          gh api --silent repos/hashicorp/consul-enterprise/dispatches \
            -f 'event_type=oss-merge' \
            -f 'client_payload[git-ref]=${{ github.ref_name }}' \
            -f 'client_payload[git-sha]=${{ github.sha }}' \
            -f 'client_payload[git-actor]=${{ github.actor }}' \
            -f 'client_payload[pr-branch]=${{ github.event.pull_request.head.label || '' }}
