# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Verify Release - Zip Files

on:
  workflow_call:
    inputs:
      package-name:
        description: 'Name of consul release package (consul vs consul-enterprise)'
        required: true
        default: 'consul'
        type: string
      version:
        description: The x.y.z version (also need to specify applicable suffixes like +ent and -dev)'
        required: true
        type: string
      runs-on:
        description: An expression indicating which kind of runners to use.
        required: true
        type: string
      zip-files:
        description: An array of zip file definitions to expect for release.
        required: true
        type: string

jobs:
  verify-zips:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: verify zips
        run: |
          ZIPS_STRING="consul_1.16.0_linux_386.zip|consul_1.16.0_linux_amd64.zip|consul_1.16.0_linux_arm.zip|consul_1.16.0_linux_arm64.zip|consul_1.16.0_freebsd_386.zip|consul_1.16.0_freebsd_amd64.zip|consul_1.16.0_windows_386.zip|consul_1.16.0_windows_amd64.zip|consul_1.16.0_solaris_amd64.zip"

          occurences=$(curl https://releases.hashicorp.com/consul/1.11.1/ \
          | grep -E "${ZIPS_STRING}" \
          | wc -l \
          | awk '$1=$1')
          
          if [[ ${occurences} != "2" ]]; then
            echo "ERROR: incorrect number of zip files found"
            exit 1
          fi
          
          
