# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Verify Release - Zip Files

on:
  workflow_call:
    inputs:
      package-name:
        description: 'Name of consul release package (consul vs consul-enterprise)'
        required: true
        default: 'consul'
        type: string
      version:
        description: The x.y.z version (also need to specify applicable suffixes like +ent and -dev)'
        required: true
        type: string
      runs-on:
        description: An expression indicating which kind of runners to use.
        required: true
        type: string
      zip-files:
        description: An array of zip file definitions to expect for release.
        required: true
        type: string

jobs:
  verify-zips:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: verify zips
        run: |
          zips=$(jq -r 'map(${{ inputs.package-name}} + "_" + ${{ inputs.version }} + "_" + .os + "_" + .arch + ".zip" )| join("|")' ) <<< "${{ fromJSON(inputs.zip-files) }}"
          expected=$(${{ fromJSON(inputs.zip-files) }} | jq '.results | length')
          found=$(curl https://releases.hashicorp.com/consul/1.16.0/ \
          | grep -E "${zips}" \
          | wc -l \
          | awk '$1=$1')
          
          if [[ ${found} != expected ]]; then
            echo "ERROR: incorrect number of zip files found. Expected: ${expected}. Found: ${found}"
            exit 1
          fi
          
          
