# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Verify Release - Linux

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Name of consul release package (consul vs consul-enterprise)'
        required: true
        default: 'consul'
        type: choice
        options:
        - consul
        - consul-enterprise
      version:
        description: The x.y.z version (also need to specify applicable suffixes like +ent and -dev)'
        required: true
        type: string

jobs:
  ## TODO:
  # - get all amd64, arm64, and i386 working on debian and rpm.
  # - consolidate dockerfiles to have just an RPM versiona and debian version.
  # DEBIAN / amd64
  verify-debian-amd64-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg TARGETARCH=amd64 \
          -f ./build-support/docker/Verify-Release-Ubuntu-amd64.dockerfile .

  verify-debian-amd64-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg TARGETARCH=amd64 \
          -f ./build-support/docker/Verify-Release-Debian-amd64.dockerfile .
            
  # DEBIAN / i386
  verify-debian-i386-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg TARGETARCH=i386 \
          -f ./build-support/docker/Verify-Release-Ubuntu-i386.dockerfile .
  
  verify-debian-i386-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg TARGETARCH=i386 \
          -f ./build-support/docker/Verify-Release-Debian-i386.dockerfile .

  # DEBIAN / arm64
  verify-debian-arm64-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg TARGETARCH=arm64 \
          -f ./build-support/docker/Verify-Release-Debian-arm64.dockerfile .

  verify-debian-arm64-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg TARGETARCH=arm64 \
          -f ./build-support/docker/Verify-Release-Ubuntu-arm64.dockerfile .

  # RPM / amd64
  verify-rpm-amd64-fedora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          -f ./build-support/docker/Verify-Release-Fedora-amd64.dockerfile .

  verify-rpm-amd64-centos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          -f ./build-support/docker/Verify-Release-CentOS-amd64.dockerfile .

  verify-rpm-amd64-amazon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: docker build with version
        run: |
          docker build \
          --build-arg PACKAGE=${{ inputs.packageName }} \
          --build-arg VERSION=${{ inputs.version }} \
          -f ./build-support/docker/Verify-Release-Amazon-amd64.dockerfile .

# RPM / amd64
  