# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Verify Release Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: The x.y.z version (also need to specify applicable suffixes like +ent and -dev)'
        required: true
        type: string
      include-fips:
        description: Indicates whether we should check for FIPS binaries and docker images. Versions below 1.16.0 should be false.
        required: false
        type: boolean
        default: true

jobs:
  verify-oss-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: docker pull OSS - docker hub
        run: docker pull hashicorp/consul:${{ inputs.version }}
      - name: docker pull OSS - ECR
        run: docker pull public.ecr.aws/hashicorp/consul:${{ inputs.version }}
  verify-ent-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: docker pull ENT - docker hub
        run: docker pull hashicorp/consul-enterprise:${{ inputs.version }}-ent
      - name: docker pull ENT - ECR
        run: docker pull public.ecr.aws/hashicorp/consul-enterprise:${{ inputs.version }}-ent
  verify-fips-docker-images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # NOTE: this permission is explicitly required for Vault auth.
      contents: read
    steps:
      - name: docker pull ENT FIPS - docker hub
        run: docker pull hashicorp/consul-enterprise-fips:${{ inputs.version }}-ent.fips1402
      - name: docker pull ENT FIPS - ECR
        run: docker pull public.ecr.aws/hashicorp/consul-enterprise-fips:${{ inputs.version }}-ent.fips1402

